spring.application.name=Data-Persistence-API

server.port=8080
server.address=0.0.0.0


# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database
spring.datasource.url=${SPRING_DATA_URL}
spring.datasource.username=${SPRING_DATA_USERNAME}
spring.datasource.password=${SPRING_DATA_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# External APIs
app.agify-api-url=${AGIFY_API_URL}
app.genderize-api-url=${GENDERIZE_API_URL}
app.nationalize-api-url=${NATIONALIZE_API_URL}
